trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo 'Starting pipeline...'
    displayName: 'Starting Pipeline'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      nohup uvicorn main:app --app-dir ./fastapi --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &
    displayName: 'Run FastAPI server in background'

  # Add additional steps here for testing, linting, etc.
