trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo 'Starting pipeline...'
    displayName: 'Starting Pipeline'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      chmod +x startup.sh
      ./startup.sh
    workingDirectory: $(Build.SourcesDirectory)/fastapi
    displayName: 'Run startup script'

  # Add additional steps here for testing, linting, etc.

  # You might not need to run the FastAPI server separately if your startup script does it.
  #- script: |
  #    uvicorn fastapi.main:app --host 0.0.0.0 --port 8000
  #  displayName: 'Run FastAPI server'

  # Add deployment steps if necessary
